/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * make10.java
 *
 * Created on 2011/12/16, 21:23:55
 */
package MakeNum;

/**
 *
 * @author lindow
 */
public class Main extends javax.swing.JFrame {

    /** Creates new form make10 */
    public Main() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("4つの数字をある数にする");

        jButton1.setText("計算");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField5.setText("目標の数字（初期値：10）");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .add(jTextField5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jTextField5)
                    .add(jTextField4)
                    .add(jTextField3)
                    .add(jTextField2)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    class rational {

        //分子
        int numerator;
        //分母
        int denominator;
        String str;

        rational(int a) {
            numerator = a;
            denominator = 1;
            str = "" + a;
        }

        //空で初期化
        rational() {
        }

        // 最大公約数
        int gcd(int a, int b) {
            int m = a;
            int n = b;

            if (n > m) {
                int temp = m;
                m = n;
                n = temp;
            }
            while (n > 0) {
                int temp = n;
                n = m % n;
                m = temp;
            }
            return m;
        }

        //通分
        rational ra_reduction() {
            rational result = new rational();

            // 0 だった場合
            if (numerator == 0) {
                result.denominator = 1;
                result.numerator = 0;
                return result;
            }

            // 分母を正の数に
            if (denominator < 0) {
                result.denominator = -(denominator);
                result.numerator = -(numerator);
            } else {
                result.denominator = denominator;
                result.numerator = numerator;
            }
            //分子が負の時一端正にして約分して戻す
            int sign = 1;
            if (result.numerator < 0) {
                sign = -1;
                result.numerator *= -1;
            }
            //約分
            int factor = gcd(result.denominator, result.numerator);
            result.denominator = result.denominator / factor;
            result.numerator = result.numerator / factor;
            result.numerator *= sign;
            result.str = str;
            return result;
        }

        //分数の足し算
        rational ra_add(rational a) {
            rational result = new rational();
            result.denominator = denominator * a.denominator;
            result.numerator = numerator * a.denominator + denominator * a.numerator;
            result.str = "(" + str + "+" + a.str + ")";
            return result.ra_reduction();
        }

        // 分数の引き算
        rational ra_sub(rational a) {
            rational result = new rational();
            result.denominator = denominator * a.denominator;
            result.numerator = numerator * a.denominator - denominator * a.numerator;
            result.str = "(" + str + "-" + a.str + ")";
            return result.ra_reduction();
        }

        //分数の掛け算
        rational ra_mul(rational a) {
            rational result = new rational();
            result.denominator = denominator * a.denominator;
            result.numerator = numerator * a.numerator;
            result.str = "(" + str + "*" + a.str + ")";
            return result.ra_reduction();
        }

        //分数の割り算
        rational ra_div(rational a) {
            rational result = new rational();
            result.denominator = denominator * a.numerator;
            result.numerator = numerator * a.denominator;
            result.str = "(" + str + "/" + a.str + ")";
            return result.ra_reduction();
        }
        
        void information() {
            System.out.println(numerator + "/" + denominator); 
        }
    }

    void ra_calculate(rational ra[], int target) {
        int i, j, k, l;

        if (ra.length == 1) {
            if (ra[0].ra_sub(new rational(target)).numerator == 0 && ra[0].ra_sub(new rational(target)).denominator != 0) {
                jTextArea1.append(ra[0].str + System.getProperty("line.separator"));
            }
        }

        rational[] temp = new rational[ra.length - 1];
        //順番の入れ替え
        for (i = 0; i < ra.length - 1; i++) {
            for (j = i + 1; j < ra.length; j++) {
                l = 0;
                for (k = 0; k < ra.length; k++) {
                    if ((k != i) && (k != j)) {
                        temp[l++] = ra[k];
                    }
                }
                //足し算
                temp[l] = ra[i].ra_add(ra[j]);
                ra_calculate(temp, target);
                //引き算（順番関係あり）
                temp[l] = ra[i].ra_sub(ra[j]);
                ra_calculate(temp, target);
                temp[l] = ra[j].ra_sub(ra[i]);
                ra_calculate(temp, target);
                //掛け算
                temp[l] = ra[i].ra_mul(ra[j]);
                ra_calculate(temp, target);
                //割り算（順番関係ありかつ0判定）
                if (ra[j].numerator != 0) {
                    temp[l] = ra[i].ra_div(ra[j]);
                    ra_calculate(temp, target);
                }
                if (ra[i].numerator != 0) {
                    temp[l] = ra[j].ra_div(ra[i]);
                    ra_calculate(temp, target);
                }
            }
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            /*
            NumOp[] num = new NumOp[4];
            
            num[0] = new NumOp(Integer.parseInt(jTextField1.getText()));
            num[1] = new NumOp(Integer.parseInt(jTextField2.getText()));
            num[2] = new NumOp(Integer.parseInt(jTextField3.getText()));
            num[3] = new NumOp(Integer.parseInt(jTextField4.getText()));
            
            int target = Integer.parseInt(jTextField5.getText());
            
            calculate(num, target);
             * 
             */
            jTextArea1.setText("");
            rational[] num = new rational[4];

            num[0] = new rational(Integer.parseInt(jTextField1.getText()));
            num[1] = new rational(Integer.parseInt(jTextField2.getText()));
            num[2] = new rational(Integer.parseInt(jTextField3.getText()));
            num[3] = new rational(Integer.parseInt(jTextField4.getText()));

            int target = 10;
            if (jTextField5.getText().equals("目標の数字（初期値：10）")) {
                target = 10;
            } else {
                target = Integer.parseInt(jTextField5.getText());
            }


            ra_calculate(num, target);

        } catch (Exception e) {
            System.out.println("");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
